plugins {
    id 'com.android.application'
}

android {
    namespace 'com.notebook'   // AGP 7.4 支持 namespace 在 build.gradle 中
    compileSdk 33

    defaultConfig {
        applicationId "com.notebook"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.7.2'
    implementation 'androidx.core:core:1.10.1'
}
